// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLOJHcVNY7XLUFwO0tJd9xHWbx1SpZ2k',
    appId: '1:763693226746:web:2416102879bf0892be8743',
    messagingSenderId: '763693226746',
    projectId: 'optacloud-5044c',
    authDomain: 'optacloud-5044c.firebaseapp.com',
    storageBucket: 'optacloud-5044c.firebasestorage.app',
    measurementId: 'G-WS6VC7254T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG0y14VcaLDBB982b6-SClMOhndnxGOaE',
    appId: '1:763693226746:android:6c71e96607d27a5fbe8743',
    messagingSenderId: '763693226746',
    projectId: 'optacloud-5044c',
    storageBucket: 'optacloud-5044c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_wZbLy2BQosdw9zZXDgiyghN2SWMazPA',
    appId: '1:763693226746:ios:85e19bfca6594af9be8743',
    messagingSenderId: '763693226746',
    projectId: 'optacloud-5044c',
    storageBucket: 'optacloud-5044c.firebasestorage.app',
    androidClientId: '763693226746-p4hd21bs3boi8fd35ranp3tn0a1mqvcf.apps.googleusercontent.com',
    iosClientId: '763693226746-qssm4ljb8i01euscrj4c6oggkfsunpvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}